inherit_from: .rubocop_todo.yml

require: rubocop-rails

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - spec/models/coordenate_spec.rb

Metrics/MethodLength:
  Exclude:
    - spec/helpers/mocked_crossmint_requests_helper.rb

Style/WordArray:
  Exclude:
    - spec/helpers/mocked_crossmint_requests_helper.rb

Style/StringLiterals:
  Exclude:
    - spec/helpers/mocked_crossmint_requests_helper.rb

Layout/FirstArrayElementIndentation:
  Exclude:
    - spec/helpers/mocked_crossmint_requests_helper.rb
