inherit_from: .rubocop_todo.yml

require: rubocop-rails

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Metrics/BlockLength:
  Exclude:
    - spec/models/coordenate_spec.rb
