def mocked_goals_response_success(url)
  stub_request(:get, url).to_return body: goals_body_success.to_json, headers: { status: 200, content_type: 'application/json' }
end

def mocked_goals_response_failed
end

def goals_body_success
  {
    "goal": [
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "POLYANET",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ],
        [
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE",
            "SPACE"
        ]
    ]
  }
end
